export { default as Category } from "./Category"
export { default as CreditBloc } from "./CreditBloc"
export { CreditCalculateInf } from "./CreditCalculateInf"
export { default as CreditSearchForm } from "./CreditSearchForm"
export { default as NewNews } from "./NewNews"
export { default as QuestionsBloc } from "./QuestionsBloc"
export { TextBloc } from "./TextBloc"
export { default as SimpleSlider } from "./SectionSlider"
